### PR TITLE
37 auto queries and other fixes

### LINKED ISSUE #37: Execute the aggregation query automatically
For speed we could have an user-configurable option to execute the query whenever we have a valid request, as opposed to having to click on the "Execute" button.

### LINKED ISSUE #39: Client-side responses cache
By default, when using `size: 0`, ES caches aggregations [1] but it would be useful to cache aggregations so that we don't have to make unuseful requests if we have the results on a cache.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/caching-heavy-aggregations.html -> https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html

### PR DESCRIPTION
**Pull request by saabi**
closes #37 
closes #39

### CODE REVIEW

File: src/routes/builder/index.svelte [hunk 1]
```diff
@@ -18,6 +18,11 @@
 		capitalize
 	} from 'app/utils';
 
+	// The data computed below only changes once after `npm run makedata`,
```
Comment (mindrones) [inline src/routes/builder/index.svelte]: I'd open an issue about this and remove this comment

File: src/routes/builder/index.svelte [hunk 2]
```diff
@@ -184,54 +190,54 @@
...
 	}
 
+	function cleanRequestBody () {
+		readyForRequest = false;
+		queryTemplate = {
+			size: 0
+		}
+	}
+
+	function isMissing (dicts, set, value) {
```
Comment (mindrones) [inline src/routes/builder/index.svelte]: aah great :)
I'd rename: `dicts` -> `objs`, `set` -> `key` and dict` -> `obj`

File: src/routes/builder/index.svelte [hunk 3]
```diff
@@ -257,27 +263,42 @@
...
-		const endpoint = getEndpointURL(DATASETS[queryConfig.dataset]);
-		const url = `${endpoint}/_search`;
-		responsePromise = request(fetch, 'POST', url, {data: parsedQuery});
+		if (readyForRequest) {
+			const endpoint = getEndpointURL(DATASETS[queryConfig.dataset]);
+			const url = `${endpoint}/_search`;
+			// TODO cache manage here
+			// perhaps store results with URL + request body JSON as string key
+			const cacheKey = `${url}/${JSON.stringify(parsedQuery)}`;
+			console.log(cacheKey);
```
Comment (mindrones) [inline src/routes/builder/index.svelte]: I'd remove the 2 `console.log` here

File: src/routes/builder/index.svelte [hunk 4]
```diff
@@ -257,27 +263,42 @@
...
+			console.log(cacheKey in cache && cache[cacheKey]);
+
+			if (cacheKey in cache) {
+				responsePromise = Promise.resolve(cache[cacheKey]);
+			}
+			else {
```
Comment (mindrones) [inline src/routes/builder/index.svelte]: I'd format as `} else` here

**Review by mindrones — APPROVED** [review]
Great, good to merge apart from minor changes in the comments below.
I would add also update the change log under v0.0.5.

Thanks!
